name: hr_management_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.4.3 <4.0.0'

dependencies:
    bloc: ^8.1.4
    buffer: ^1.2.3
    calendar_date_picker2: ^1.1.2
    dio: ^5.4.3+1
    docx_template: ^0.4.0
    file_picker: ^8.0.5
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.6
    flutter_localization: ^0.2.0
    flutter_secure_storage: ^9.2.2
    image: ^4.2.0
    path_provider: ^2.1.3
    pdf: ^3.10.8

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - images/
    fonts:
        - family: Hacen-Liner-Print-out
          fonts:
              - asset: fonts/Hacen-Liner-Print-out.ttf
        - family: Cairo
          fonts:
              - asset: fonts/Cairo.ttf
